projet_admin:
    resource: "@ProjetAdminBundle/Resources/config/routing.yml"
    prefix:   /


login:
    pattern:   /admin/login
    defaults:  { _controller: ProjetAdminBundle:Security:login }

login_check:
    pattern:   /admin/login_check

logout:
    pattern:   /admin/logout