security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Projet\AdminBundle\Entity\Utilisateur: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class:  Projet\AdminBundle\Entity\Utilisateur, property: username }
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern:    ^/admin/*
            provider: main
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: /admin/accueil
                csrf_provider: form.csrf_provider
            logout:
                path:   logout
                target: /login
            anonymous: true
            security: true
            remember_me:
                key:      "%secret%"
                lifetime: 3600 # en secondes
                path:     /
                domain:   ~

        login:
            pattern:  ^/login
            anonymous: true
        


    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http }
       #- { path: ^/admin/accueil, roles: ROLE_USER, requires_channel: http }
        - { path: ^/admin/*, roles: ROLE_ADMIN, requires_channel: http }
