<?php

namespace Projet\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CgvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CgvRepository extends EntityRepository
{
}
