<?php

namespace Projet\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Projet\AdminBundle\ProjetAdminBundle;

/**
 * InfoSuppProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoSuppProduitRepository extends EntityRepository
{
	public function findInfoByCouleurTaille($c,$t){
		$qb = $this->getEntityManager()->createQuery(
			"SELECT i FROM ProjetAdminBundle:InfoSuppProduit i WHERE i.couleur='".$c."'
				AND i.taille='".$t."'"
		)->getResult();
		return $qb;
	}
}
